services:
  wis2box-ftp:
    image: ghcr.io/wmo-im/wis2box-ftp
    environment:
      - FTP_USER=${FTP_USER}
      - FTP_PASS=${FTP_PASS}
      - FTP_SSL_ENABLED=${FTP_SSL_ENABLED:-FALSE}
      - LOGGING_LEVEL=${LOGGING_LEVEL:-WARNING}
      - MINIO_ENDPOINT=${WIS2BOX_STORAGE_ENDPOINT:-http://minio:9000}
      - MINIO_ROOT_USER=${WIS2BOX_STORAGE_USER:-minio}
      - MINIO_ROOT_PASSWORD=${WIS2BOX_STORAGE_PASSWORD:-minio123}
    ports:
      - '20-21:20-21/tcp'
      - '21100-21110:21100-21110/tcp'
    volumes:
      - wis2box-ftp:/home/vsftpd/
volumes:
  wis2box-ftp:
