services:
  web-proxy:
    ports:
      - 4480:80

  wis2box-ui:
    ports:
      - 9999:80

  minio:
    ports:
      - "9000:9000"
      - "9001:9001"
      - "8022:8022"
    deploy:
      replicas: 1

  mosquitto:
    ports:
      - 1883:1883
      - 8884:8884