# define virtual network to give fixed IP for loki used by the logging-driver for all containers
networks:
  vpcbr: # virtual network name
    driver: bridge
    ipam:
     config: # here, we define our ip space
       - subnet: 10.5.0.0/24
         gateway: 10.5.0.1

# this is a YAML anchor to avoid repetition
x-logging: &logging
  logging:
    driver: loki
    options: # note: the ip is the ip we will assign later to loki in this file
      loki-url: "http://10.5.0.2:3100/loki/api/v1/push"
      mode: non-blocking
      max-buffer-size: 4m
      loki-retries: "3"

services:
  # The Loki database for storing logs.
  loki:
    <<: *logging
    container_name: loki
    image: grafana/loki:2.4.1
    command: -config.file=/etc/loki/loki-config.yml
    volumes:
      - loki-data:/loki
      - ./loki/loki-config.yml:/etc/loki/loki-config.yml
    networks:
      vpcbr: # this is the place where we assign the static ipv4 address
        ipv4_address: 10.5.0.2
      default:
  # mqtt_metrics_collector, listens to mqtt-broker
  # TODO: integrate this into mqp-publisher 
  mqtt_metrics_collector:
    <<: *logging
    container_name: mqtt_metrics_collector
    env_file:
      - default.env
      - ../dev.env
    #image: ghcr.io/wmo-im/wis2box-mqtt-metrics-collector:0.4.0
    build:
      context: ./mqtt_metrics_collector
    depends_on:
      - mosquitto
    ports:
      - 8001:8001
  # prometheus to collect metrics
  prometheus:
    <<: *logging
    image: prom/prometheus:v2.37.0
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
  # cadvisor to monitor our containers!
  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk:/dev/disk/:ro
    depends_on:
      - wis2box
  # Grafana, graphical monitoring dashboards for wis2box using data from loki and prometheus
  grafana:
    <<: *logging
    container_name: grafana
    env_file:
      - ../dev.env
    image: grafana/grafana-oss:9.0.3
    volumes:
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_HIDE_VERSION=true
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/etc/grafana/provisioning/dashboards/home.json
      - GF_ANALYTICS_CHECK_FOR_UPDATES=false
      - GF_USERS_VIEWERS_CAN_EDIT=true
      - GF_UNIFIED_ALERTING_ENABLED=false
      - GF_ALERTING_ENABLED=false
      - GF_USERS_DEFAULT_THEME=dark
      - GF_DISABLE_SIGNOUT_MENU=true
      - GF_SERVER_ROOT_URL=${WIS2BOX_URL:-http://localhost:8999}/monitoring
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    ports:
      - 3000:3000
  wis2box:
    <<: *logging
  mosquitto:
    <<: *logging
  wis2box-api:
    <<: *logging
  elasticsearch:
    <<: *logging
  wis2box-auth:
    <<: *logging
  minio:
    <<: *logging

volumes:
  loki-data:
  prometheus-data:
